# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deployment
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Dump Event JSON
        env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: echo $EVENT_CONTEXT
