# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  deployment:

  deployment_status:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Event JSON
        env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: echo $EVENT_CONTEXT
      - run: echo Hello world
