name: Deployment

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: foo
    env:
      GITHUB_JSON: ${{toJSON(github)}}
    steps:
      - name: Dump Event JSON
        env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: echo $EVENT_CONTEXT
