# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "ESLint Analysis"
on:
  pull_request:
    paths:
      - "**/aura/**"
      - "**/lwc/**"
jobs:
  run-eslint:
    name: ESLint Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run NPM install
        run: npm install
      - name: Run ESLint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JQ_QUERY_GITHUB: >
            .files | map(.path)[] | select(contains("/aura/") or contains("/lwc/"))
          JQ_QUERY_ESLINT: |
            .[] | . as $row | .messages | map({
              severity: (
                if .severity < 2 then "error"
                elif .severity < 5 then "warn"
                else "notice"
                end
              ),
              values: [
                { key: "file", value:($row.filePath | ltrimstr($root)) },
                { key: "line", value: .line },
                { key: "endLine", value: .endLine },
                { key: "col", value: .column },
                { key: "endColumn", value: .endColumn },
                { key: "title", value: "\(.ruleId)::\(.message)" }
              ]
            })[]| "::\(.severity) \(.values | map("\(.key)=\(.value)") | join(","))"
        run: |
          gh pr view ${{ github.event.number }} --json files --jq "$JQ_QUERY_GITHUB" |
          xargs node_modules/.bin/eslint -f json |
          jq --arg root "${{ github.workspace }} -r "$JQ_QUERY_ESLINT"
