# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "ESLint Analysis"
on:
  pull_request:
    paths:
      - "**/aura/**"
      - "**/lwc/**"
jobs:
  eslint:
    name: ESLint Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run NPM install
        run: npm install
      - name: Run ESLint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JQ_QUERY_GITHUB: |
            .files | map(.path)[] | select(contains("/aura/") or contains("/lwc/"))
          JQ_QUERY_ESLINT_FILTER_FILE: ./.github/workflows/eslint-jquery-filter.txt
        run: |
          gh pr view ${{ github.event.number }} --json files --jq "$JQ_QUERY_GITHUB" |
          xargs node_modules/.bin/eslint -f json |
          jq --arg root -f "$JQ_QUERY_ESLINT_FILTER_FILE" -r "$JQ_QUERY_ESLINT"
