# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed
      - reopened
      - synchronize
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Event JSON
        env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $EVENT_CONTEXT
  reuse-without-input:
    uses: ./.github/workflows/reusable.yml
  reuse-with-input:
    uses: ./.github/workflows/reusable.yml
    with:
      event-json: ${{ toJSON(github.event) }}
