on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed
      - reopened
      - synchronize
jobs:
  something:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Event JSON
        shell: bash
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
