# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed
      - reopened
      - synchronize
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Event JSON
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
  gh-check:
    runs-on: ubuntu-latest
    steps:
      - run: gh --version
  commit:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    steps:
      - run: gh --version
