# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Merge Upstream
on:
  workflow_call:
    inputs:
      upstream:
        description: The name of the branch to merge into
        required: true
        type: string
jobs:
  merge-upstream:
    name: Merge into ${{ inputs.upstream }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.upstream }}
          fetch-depth: 0
      - id: merge
        name: Merge
        env:
          GIT_AUTHOR_NAME: ${{ github.event.pull_request.merged_by }}
          GIT_AUTHOR_DATE: ${{ github.event.pull_request.merged_at }}
          HEAD_SHA: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
          MERGE_MSG: |
            Merge pull request #${{ github.event.number }} into ${{ inputs.upstream }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge --no-ff -m "$MERGE_MSG" $HEAD_SHA
      - name: Push
        if: github.event.pull_request.merged == true
        run: git push
permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none
