# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Merge Upstream
on:
  pull_request:
    branches:
      - main
      - ciandt/dev-portal
      - forefront-inc/b2b-ltng
    types:
      - opened
      - closed
      - synchronize
      - reopened
jobs:
  merge-upstream:
    strategy:
      fail-fast: true
      matrix:
        upstream:
          - "truckin/int"
          - "truckin/qa"
    name: ${{ matrix.upstream }}
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ${{ github.event.pull_request.merged_by || github.actor }}
      GIT_AUTHOR_DATE: ${{ github.event.pull_request.merged_at }}
      HEAD_SHA: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.upstream }}
          fetch-depth: 0
      - id: merge
        name: Merge
        env:
          MERGE_MSG: |
            Merge pull request #${{ github.event.number }} into ${{ matrix.upstream }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin $HEAD_SHA
          git merge --no-ff -m "$MERGE_MSG" $HEAD_SHA
      - name: Push
        if: github.event.pull_request.merged == true
        run: git push
