# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Merge Upstream
on:
  pull_request:
    branches:
      - main
      - ciandt/dev-portal
      - forefront-inc/b2b-ltng
    types:
      - opened
      - closed
      - synchronize
      - reopened
env:
  GIT_COMMITTER_NAME: github-actions
  GIT_COMMITTER_EMAIL: github-actions@github.com
  GIT_AUTHOR_NAME: ${{ github.event.pull_request.merged_by || github.actor }}
  GIT_AUTHOR_DATE: ${{ github.event.pull_request.merged_at }}
  HEAD_SHA: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
  MERGE_MSG: |
    Merge pull request #${{ github.event.number }}
concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  int:
    name: truckin/int
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: truckin/int
          fetch-depth: 0
      - name: Fetch
        run: git fetch origin $HEAD_SHA
      - name: Merge
        run: git merge --no-ff -m "$MERGE_MSG" $HEAD_SHA
      - name: Push
        if: github.event.pull_request.merged == true
        run: git push
  qa:
    needs:
      - int
    name: truckin/qa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: truckin/qa
          fetch-depth: 0
      - name: Fetch
        run: git fetch origin $HEAD_SHA
      - name: Merge
        run: git merge --no-ff -m "$MERGE_MSG" $HEAD_SHA
      - name: Push
        if: github.event.pull_request.merged == true
        run: git push
