# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  pull_request:
    types:
      - edited
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: cat $GITHUB_EVENT_PATH	
